### ISSUE TITLE
GFM - mdl reads unchecked box as link

### ISSUE THREAD

**Issue by davidosomething** [markdownlint/markdownlint#90] opened 2015-05-14 19:33 UTC
```
- [ ] item
```

should render like this:
- [x] item

but mdl expects it to be a link `[name](http://google.com)`

**Comment by mivok** [comment] 2015-05-14 19:36
This probably applies to a checked box too.

**Comment by NaomiReeves** [comment] 2019-12-02 09:05
Duplicate of #264 and I'm choosing to keep the newer one just because we have the context and active discussion in that thread.

**Closed as completed** 2019-12-02 09:05 UTC
Labels: bug, duplicate
