### ISSUE TITLE
Consider allowing exceptions for rule MD033 "Inline HTML"

### ISSUE THREAD

**Issue by DavidAnson** [markdownlint/markdownlint#118] opened 2016-01-15 06:23 UTC
I made this change to the Node.js implementation in response to a user request:
DavidAnson/markdownlint#3

Details, code, and test cases can be found in the commit:
DavidAnson/markdownlint@fb31bb5f350ce76550377c6d84b3834aee269ee8

**Comment by devth** [comment] 2016-03-11 04:23
:+1: must have

**Comment by wbadart** [comment] 2020-04-22 20:50
For bookkeeping: related to #189

**Comment by guillaume-d** [comment] 2021-01-03 22:30
> For bookkeeping: related to #189

More than that, #189 is just a pure duplicate of this.
Why dilute the votes? Someone, please close #189.

**Closed as completed** 2023-03-21 16:05 UTC
Labels: enhancement, rule update
