### ISSUE TITLE
Add an allow list of HTML tags parameter for Rule 33

### ISSUE THREAD

**Issue by barnett** [markdownlint/markdownlint#359] opened 2020-10-06 19:17 UTC
## New Rule Checklist

Before suggesting a rule for inclusion please make sure your suggestion meets these criteria for rule built into markdownlint:
 - [x] allows a user to lint for a specific syntax divergence across the multiple flavors and styles of markdown
 - [x] does not dictate any one specific style, but enables an end user to enable, disable, or configure the specific style of enforcement desired

## Describe The Rule:
Sometimes markdown lacks handling of certain needed output html, such as [a newline within a table](https://stackoverflow.com/a/12119310/2487496). Thus to handle this, we need to allow just this one html tag but want to avoid opening all other tags still. Thinking it'd be most applicable as a parameter to [Rule 33](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md033---inline-html).

## Why Should This Be Included In Markdownlint?:
Seems a common flow that would be backward compatible and allow ultimate flexibility.

## Can We Help You Implement This?:
Am interested in helping but haven't dug too deeply into it yet. Will do later this week.

**Comment by DavidAnson** [comment] 2020-10-06 19:55
Please try to be consistent with https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033 if possible, thanks!

**Comment by guillaume-d** [comment] 2021-01-03 22:41
Duplicate of #118, please close as such.

**Closed as completed** 2021-01-04 02:07 UTC
Labels: duplicate, new rule
