### ISSUE TITLE
kramdown version seems to conflict with Jekyll 4.0.0

### ISSUE THREAD

**Issue by XhmikosR** [markdownlint/markdownlint#266] opened 2019-09-06 08:03 UTC
```Gemfile
source 'https://rubygems.org'

gem 'html-proofer', '~> 3.12.0'
gem 'jekyll', '~> 4.0.0'
gem 'jekyll-feed', '~> 0.12.1'
gem 'jekyll-paginate', '~> 1.1.0'
gem 'jekyll-seo-tag', '~> 2.6.1'
gem 'jekyll-sitemap', '~> 1.3.1'
gem 'mdl', :git => 'https://github.com/markdownlint/markdownlint.git', :ref => '925eadb'
gem 'tzinfo-data', '~> 1.2019.2'
gem 'wdm', '~> 0.1.1', :install_if => Gem.win_platform?
```

results in:

```
C:\Users\xmr\Desktop\blog>bundle up
Fetching https://github.com/markdownlint/markdownlint.git
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "kramdown":
  In Gemfile:
    jekyll (~> 4.0.0) was resolved to 4.0.0, which depends on
      kramdown (~> 2.1)

    mdl was resolved to 0.5.0, which depends on
      kramdown (>= 1.12.0, ~> 1.12)
```

BTW I have resolved to use the specific git commit due to #224 which is fixed in master but we don't have a new gem released.

**Comment by mide** [comment] 2019-09-07 01:28
I found my way to this same issue - It's caused by the `~> 1.12`. Unfortunately, I don't know what the requirements really are for this project. https://github.com/markdownlint/markdownlint/blob/a9e80fcf3989d73b654b00bb2225a00be53983e8/mdl.gemspec#L23

**Comment by jaymzh** [comment] 2019-10-21 15:41
Fix merged, will close this when the next version is released.

**Comment by jaymzh** [comment] 2019-11-09 02:42
Oops forgot to close this when we did the last release. :)

**Closed as completed by jaymzh** 2019-11-09 02:42 UTC
Labels: awaiting release
